//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3607
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iPlaylist.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iPlaylist.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album: {0}.
        /// </summary>
        internal static string CurrentAlbumFormat {
            get {
                return ResourceManager.GetString("CurrentAlbumFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No album.
        /// </summary>
        internal static string CurrentNoAlbum {
            get {
                return ResourceManager.GetString("CurrentNoAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string DefaultStatus {
            get {
                return ResourceManager.GetString("DefaultStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error!.
        /// </summary>
        internal static string FatalErrorTitle {
            get {
                return ResourceManager.GetString("FatalErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language change will be applied when you restart iPlaylist..
        /// </summary>
        internal static string LanguageChangeText {
            get {
                return ResourceManager.GetString("LanguageChangeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language change.
        /// </summary>
        internal static string LanguageChangeTitle {
            get {
                return ResourceManager.GetString("LanguageChangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPlaylist needs you to fill application settings!.
        /// </summary>
        internal static string NotifyBaloonSettings {
            get {
                return ResourceManager.GetString("NotifyBaloonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPlaylist is now collecting your music preferences....
        /// </summary>
        internal static string NotifyBaloonText {
            get {
                return ResourceManager.GetString("NotifyBaloonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPlaylist v{0} ({1}).
        /// </summary>
        internal static string NotifyBaloonTitleFormat {
            get {
                return ResourceManager.GetString("NotifyBaloonTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to media player is interrupted.
        ///
        ///{0}
        ///
        ///This could happen if you closed the media player when iPlaylist is running (which you shouldn&apos;t do). 
        ///You could restart iPlaylist..
        /// </summary>
        internal static string PlaybackInterruptedFormat {
            get {
                return ResourceManager.GetString("PlaybackInterruptedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPlaylist created shuffled playlist for you using information about your musical preferences.
        /// </summary>
        internal static string PlaylistCompleteBaloonTextFormat {
            get {
                return ResourceManager.GetString("PlaylistCompleteBaloonTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPlaylist v{0} ({1})
        ///Shuffled!.
        /// </summary>
        internal static string PlaylistCompleteNotifyFormat {
            get {
                return ResourceManager.GetString("PlaylistCompleteNotifyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPlaylist created shuffled playlist for you.
        /// </summary>
        internal static string PlaylistCompleteStatus {
            get {
                return ResourceManager.GetString("PlaylistCompleteStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPlaylist v{0} ({1})
        ///Shuffling....
        /// </summary>
        internal static string PlaylistGenerationNotifyFormat {
            get {
                return ResourceManager.GetString("PlaylistGenerationNotifyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPlaylist is generating shuffled playlist....
        /// </summary>
        internal static string PlaylistGenerationStatus {
            get {
                return ResourceManager.GetString("PlaylistGenerationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% (played: {1}, skipped: {2}).
        /// </summary>
        internal static string PlaylistQualityFormat {
            get {
                return ResourceManager.GetString("PlaylistQualityFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///
        ///Please, report this error to developers. iPlaylist will be closed now.
        ///
        ///This error could happen if you do not have correct media player installed. 
        ///In this case, select correct media player after restart..
        /// </summary>
        internal static string PluginErrorFormat {
            get {
                return ResourceManager.GetString("PluginErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to genres: {0}, artists: {1}, albums: {2}, tracks: {3}.
        /// </summary>
        internal static string RatingLabelFormat {
            get {
                return ResourceManager.GetString("RatingLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.{1:00}:{2:00}:{3:00}, total tracks: {4}.
        /// </summary>
        internal static string SourceDurationFormat {
            get {
                return ResourceManager.GetString("SourceDurationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPlaylist v{0} ({1})
        ///Rate samples: {2}.
        /// </summary>
        internal static string StatsNotifyFormat {
            get {
                return ResourceManager.GetString("StatsNotifyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (system language).
        /// </summary>
        internal static string SystemLocale {
            get {
                return ResourceManager.GetString("SystemLocale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.{1:00}:{2:00}:{3:00}, time since last shuffle: {4}.{5:00}:{6:00}:{7:00}.
        /// </summary>
        internal static string TimeOnlineFormat {
            get {
                return ResourceManager.GetString("TimeOnlineFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPlaylist is checking for updates....
        /// </summary>
        internal static string UpdateCheckStatus {
            get {
                return ResourceManager.GetString("UpdateCheckStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPlaylist is downloading update....
        /// </summary>
        internal static string UpdateDownloadingStatus {
            get {
                return ResourceManager.GetString("UpdateDownloadingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPlaylist update failed!.
        /// </summary>
        internal static string UpdateFailedStatus {
            get {
                return ResourceManager.GetString("UpdateFailedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPlaylist is up to date.
        /// </summary>
        internal static string UpdatesNotFoundStatus {
            get {
                return ResourceManager.GetString("UpdatesNotFoundStatus", resourceCulture);
            }
        }
    }
}
