//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3607
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iPlaylist.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PlayerControls {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlayerControls() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iPlaylist.Resources.PlayerControls", typeof(PlayerControls).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now playing: {0} [{1}:{2:00}].
        /// </summary>
        internal static string NowPlayingFormat {
            get {
                return ResourceManager.GetString("NowPlayingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now playing.
        /// </summary>
        internal static string NowPlayingTitle {
            get {
                return ResourceManager.GetString("NowPlayingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player is inactive.
        /// </summary>
        internal static string PlayerInactive {
            get {
                return ResourceManager.GetString("PlayerInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}   -   {1}.
        /// </summary>
        internal static string RotationFormat {
            get {
                return ResourceManager.GetString("RotationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause playback.
        /// </summary>
        internal static string TitlePause {
            get {
                return ResourceManager.GetString("TitlePause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start/continue playback.
        /// </summary>
        internal static string TitlePlay {
            get {
                return ResourceManager.GetString("TitlePlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} [{1}:{2:00}]
        ///Album: {3}.
        /// </summary>
        internal static string ToolTipFormat {
            get {
                return ResourceManager.GetString("ToolTipFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} [{1}:{2:00}].
        /// </summary>
        internal static string ToolTipNoAlbumFormat {
            get {
                return ResourceManager.GetString("ToolTipNoAlbumFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause playback.
        /// </summary>
        internal static string ToolTipPause {
            get {
                return ResourceManager.GetString("ToolTipPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start/continue playback.
        /// </summary>
        internal static string ToolTipPlay {
            get {
                return ResourceManager.GetString("ToolTipPlay", resourceCulture);
            }
        }
    }
}
